"use client";

import Link from "next/link";
import { useAuth } from "@clerk/nextjs";
import { useCallback, useEffect, useState } from "react";
import ProductMediaManager from "../../components/product-media-manager";

type Store = { id: string; name: string; slug: string; description: string; city: string };
type Category = { id: string; name: string; slug: string };
type VariantDraft = { name: string; sku: string; price: string; attributes: string };
type Variant = { id: string; name: string; sku: string; price: number; attributes: { key: string; value: string }[] };
type Product = { id: string; title: string; description: string; price: number; category: Category; attributes: { key: string; value: string }[]; variants: Variant[] };

export default function StoreManagerPage() {
  const { getToken } = useAuth();
  const [stores, setStores] = useState<Store[]>([]);
  const [products, setProducts] = useState<Record<string, Product[]>>({});
  const [categories, setCategories] = useState<Category[]>([]);
  const [storeForm, setStoreForm] = useState({ name: "", description: "", city: "Bengaluru" });
  const [productForm, setProductForm] = useState({ title: "", description: "", price: "", categoryId: "", attributes: "" });
  const [variants, setVariants] = useState<VariantDraft[]>([{ name: "Standard", sku: "", price: "", attributes: "" }]);
  const [activeStore, setActiveStore] = useState("");
  const [notice, setNotice] = useState("");

  const request = useCallback(async (path: string, init: RequestInit = {}) => { const token = await getToken(); const headers = new Headers(init.headers); if (token) headers.set("Authorization", `Bearer ${token}`); return fetch(path, { ...init, headers }); }, [getToken]);
  const load = useCallback(async () => { const response = await request("/api/me/stores"); const data = await response.json(); if (response.ok) { setStores(data.stores); setActiveStore((current) => current || data.stores[0]?.id || ""); } else setNotice(data.error); }, [request]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void fetch("/api/categories").then(async (response) => { const data = await response.json(); if (response.ok) { setCategories(data.categories); setProductForm((current) => ({ ...current, categoryId: current.categoryId || data.categories[0]?.id || "" })); } }); }, []);
  useEffect(() => { if (!activeStore) return; void request(`/api/stores/${activeStore}/products`).then(async (response) => { const data = await response.json(); if (response.ok) setProducts((current) => ({ ...current, [activeStore]: data.products })); }); }, [activeStore, request]);
  async function createStore(event: React.FormEvent) { event.preventDefault(); const response = await request("/api/stores", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(storeForm) }); const data = await response.json(); if (!response.ok) return setNotice(data.error); setStoreForm({ name: "", description: "", city: "Bengaluru" }); setNotice("Public store created."); await load(); setActiveStore(data.store.id); }
  function attributesFrom(text: string) { return text.trim() ? text.split(",").map((part) => { const [key, ...value] = part.split("="); return { key, value: value.join("=") }; }) : []; }
  function updateVariant(index: number, field: keyof VariantDraft, value: string) { setVariants((current) => current.map((variant, position) => position === index ? { ...variant, [field]: value } : variant)); }
  async function createProduct(event: React.FormEvent) { event.preventDefault(); if (!activeStore) return; const response = await request(`/api/stores/${activeStore}/products`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...productForm, price: Number(productForm.price), attributes: attributesFrom(productForm.attributes), variants: variants.map((variant) => ({ ...variant, price: Number(variant.price), attributes: attributesFrom(variant.attributes) })) }) }); const data = await response.json(); if (!response.ok) return setNotice(data.error); setProductForm({ title: "", description: "", price: "", categoryId: categories[0]?.id || "", attributes: "" }); setVariants([{ name: "Standard", sku: "", price: "", attributes: "" }]); setProducts((current) => ({ ...current, [activeStore]: [data.product, ...(current[activeStore] ?? [])] })); setNotice("Product published with purchasable variants and unique SKUs."); }
  const selected = stores.find((store) => store.id === activeStore);
  return <main className="stores-manager">
    <header><Link href="/dashboard">← Seller workspace</Link> · <Link href="/dashboard/warehouses">Warehouses & inventory</Link><p>SELLER STORES</p><h1>Build your public storefront.</h1><span>Publish categorized products with purchasable variants.</span></header>
    <section className="grid"><form onSubmit={createStore}><h2>Create a store</h2><label>Name<input required value={storeForm.name} onChange={(e) => setStoreForm({ ...storeForm, name: e.target.value })} /></label><label>Description<textarea required value={storeForm.description} onChange={(e) => setStoreForm({ ...storeForm, description: e.target.value })} /></label><label>City<input required value={storeForm.city} onChange={(e) => setStoreForm({ ...storeForm, city: e.target.value })} /></label><button>Create public store</button></form><section><h2>Your stores</h2>{stores.length === 0 ? <p>No stores yet.</p> : <div className="store-list">{stores.map((store) => <button className={store.id === activeStore ? "selected" : ""} key={store.id} onClick={() => setActiveStore(store.id)}><b>{store.name}</b><span>{store.city}</span></button>)}</div>}{selected && <a href={`/stores/${selected.slug}`} target="_blank" rel="noreferrer">Open public store ↗</a>}</section></section>
    {selected && <section className="product-editor"><form onSubmit={createProduct}><h2>Add a product to {selected.name}</h2><label>Title<input required value={productForm.title} onChange={(e) => setProductForm({ ...productForm, title: e.target.value })} /></label><label>Category<select required value={productForm.categoryId} onChange={(e) => setProductForm({ ...productForm, categoryId: e.target.value })}>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Description<textarea required value={productForm.description} onChange={(e) => setProductForm({ ...productForm, description: e.target.value })} /></label><label>Searchable product attributes<input value={productForm.attributes} onChange={(e) => setProductForm({ ...productForm, attributes: e.target.value })} placeholder="Brand=Apple, RAM Size=16 GB" /></label><label>Base price (₹)<input required type="number" min="1" value={productForm.price} onChange={(e) => setProductForm({ ...productForm, price: e.target.value })} /></label><h3>Purchasable variants</h3>{variants.map((variant, index) => <fieldset key={index}><legend>Variant {index + 1}</legend><label>Name<input required value={variant.name} onChange={(e) => updateVariant(index, "name", e.target.value)} placeholder="Black / 128 GB" /></label><label>Unique SKU<input required value={variant.sku} onChange={(e) => updateVariant(index, "sku", e.target.value)} placeholder="PHONE-BLACK-128" /></label><label>Variant price (₹)<input required type="number" min="1" value={variant.price} onChange={(e) => updateVariant(index, "price", e.target.value)} /></label><label>Variant attributes<input value={variant.attributes} onChange={(e) => updateVariant(index, "attributes", e.target.value)} placeholder="Color=Black, Storage=128 GB" /></label>{variants.length > 1 && <button type="button" className="remove" onClick={() => setVariants((current) => current.filter((_, position) => position !== index))}>Remove variant</button>}</fieldset>)}<button type="button" className="secondary" onClick={() => setVariants((current) => [...current, { name: "", sku: "", price: "", attributes: "" }])}>Add another variant</button><button>Publish product</button></form><div><h2>Published products</h2>{(products[activeStore] ?? []).length === 0 ? <p>No products yet.</p> : products[activeStore].map((product) => <article key={product.id}><ProductMediaManager productId={product.id} title={product.title} request={request} /><b>{product.title}</b><span>{product.category.name} · from ₹{product.price.toLocaleString("en-IN")}</span><p>{product.description}</p>{product.variants.length > 0 && <ul>{product.variants.map((variant) => <li key={variant.id}><b>{variant.name}</b> · {variant.sku} · ₹{variant.price.toLocaleString("en-IN")}{variant.attributes.length > 0 && ` · ${variant.attributes.map((attribute) => `${attribute.key}: ${attribute.value}`).join(", ")}`}</li>)}</ul>}</article>)}</div></section>}
    {notice && <p className="notice">{notice}</p>}
    <style>{`.stores-manager{min-height:100vh;background:#f8f7f1;color:#17251f;padding:0 5vw 70px}.stores-manager header,.stores-manager .grid,.product-editor,.stores-manager>.notice{max-width:1040px;margin-left:auto;margin-right:auto}.stores-manager header{padding:65px 0 30px;border-bottom:1px solid #dfe2d9}.stores-manager header a,.stores-manager a{color:#1f8a58;font-size:13px;font-weight:700;text-decoration:none}.stores-manager header p{font:600 10px ui-monospace,monospace;letter-spacing:.13em;color:#1f8a58;margin:32px 0 8px}.stores-manager h1{font-size:52px;letter-spacing:-3px;margin:0 0 12px}.stores-manager header span,.stores-manager p{color:#68746e}.grid,.product-editor{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:28px}.grid>form,.grid>section,.product-editor>form,.product-editor>div{background:#fff;border:1px solid #e4e5df;border-radius:18px;padding:24px}.stores-manager h2{margin:0 0 15px;font-size:23px}.stores-manager h3{font-size:15px;margin:24px 0 8px}.stores-manager label{display:grid;gap:6px;font-size:12px;font-weight:700;margin:12px 0}.stores-manager input,.stores-manager textarea,.stores-manager select{border:1px solid #d8ddd6;border-radius:9px;padding:10px;font:inherit;background:#fff}.stores-manager textarea{min-height:88px}.stores-manager button{border:0;border-radius:9px;background:#17251f;color:#fff;padding:10px 12px;font-weight:700;margin:5px 0}.stores-manager button.secondary{background:#e8eee1;color:#17251f}.stores-manager button.remove{background:none;color:#b42318;padding:0}.product-editor fieldset{border:1px solid #e4e5df;border-radius:10px;padding:8px 12px;margin:12px 0}.product-editor legend{font-size:12px;font-weight:700}.store-list{display:grid;gap:8px;margin-bottom:15px}.store-list button{display:grid;text-align:left;background:#edf0ea;color:#17251f}.store-list button.selected{background:#d9fa6a}.store-list span,.product-editor article span,.product-editor article li{font-size:12px;color:#68746e}.product-editor article{border-top:1px solid #edf0ea;padding:12px 0;display:grid;gap:5px}.product-editor article p{font-size:12px;margin:0}.product-editor ul{margin:4px 0;padding-left:16px;display:grid;gap:4px}.notice{margin-top:18px;color:#1f8a58}@media(max-width:700px){.stores-manager{padding:0 20px 40px}.stores-manager h1{font-size:40px}.grid,.product-editor{grid-template-columns:1fr}}`}</style>
  </main>;
}
